### PR TITLE
Mention GNU Radio 3.9 support in readme

### PR DESCRIPTION
**Pull request by AsciiWolf**
/cc @argilo

### CODE REVIEW

**Comment by AsciiWolf** [comment]
@argilo Let me know if there are any problems with this PR. Thanks!

**Comment by AsciiWolf** [comment]
Is there anything preventing this simple PR from being merged?

**Comment by argilo** [comment]
Sorry for the delay in getting to this. I've updated the readme to include all supported versions (including 3.10).

**Comment by AsciiWolf** [comment]
Thanks! :-)

**Pull request closed without merging**
